version: "3.9"

services:
  api:
    build: .
    container_name: coffeeshop_api
    ports:
      - "8080:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: "http://+:8080"
      DB_CONNECTION: "${DB_CONNECTION}"
      FRONTEND_URL: "${FRONTEND_URL}"
    env_file:
      - .env
    restart: on-failure